/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question to AI agents */
        post: operations["askQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repo/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload repository for analysis */
        post: operations["uploadRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repo/{repoId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get repository indexing status */
        get: operations["getRepoStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/{repoId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get knowledge graph data */
        get: operations["getGraphData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify code with tests */
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user sessions */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user repositories */
        get: operations["getRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AskQuestionRequest: {
            question: string;
            sessionId: string;
            repoId?: string;
            socraticMode?: boolean;
            /** @enum {string} */
            skillLevel?: "beginner" | "intermediate" | "advanced";
        };
        AskQuestionResponse: {
            streamUrl?: string;
            messageId?: string;
        };
        UploadRepoResponse: {
            repoId?: string;
            status?: string;
        };
        RepoStatus: {
            repoId?: string;
            /** @enum {string} */
            status?: "pending" | "indexing" | "completed" | "failed";
            progress?: number;
            currentFile?: string;
            fileCount?: number;
            totalSize?: number;
            /** Format: date-time */
            lastIndexed?: string;
        };
        GraphData: {
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
        };
        GraphNode: {
            id?: string;
            /** @enum {string} */
            type?: "file" | "class" | "function";
            label?: string;
            filePath?: string;
            lineNumber?: number;
        };
        GraphEdge: {
            id?: string;
            source?: string;
            target?: string;
            /** @enum {string} */
            type?: "imports" | "calls" | "extends" | "implements";
        };
        VerifyCodeRequest: {
            code: string;
            language: string;
            repoId?: string;
        };
        VerifyCodeResponse: {
            results?: components["schemas"]["TestResult"][];
            summary?: components["schemas"]["TestSummary"];
        };
        TestResult: {
            suite?: string;
            name?: string;
            /** @enum {string} */
            status?: "passed" | "failed" | "skipped";
            duration?: number;
            error?: string;
            stackTrace?: string;
        };
        TestSummary: {
            total?: number;
            passed?: number;
            failed?: number;
            skipped?: number;
            coverage?: number;
        };
        Session: {
            id?: string;
            title?: string;
            lastMessage?: string;
            /** Format: date-time */
            timestamp?: string;
            repoId?: string;
        };
        Repository: {
            id?: string;
            name?: string;
            status?: string;
            fileCount?: number;
            totalSize?: number;
            /** Format: date-time */
            lastIndexed?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    askQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description SSE stream URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskQuestionResponse"];
                };
            };
        };
    };
    uploadRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Repository uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadRepoResponse"];
                };
            };
        };
    };
    getRepoStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoStatus"];
                };
            };
        };
    };
    getGraphData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description Verification results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeResponse"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    getRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of repositories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
        };
    };
}
